backend:
  name: git-gateway
  branch: master

local_backend:
  url: http://localhost:8081/api/v1

media_folder: "images/uploads" # Media files will be stored in the repo under images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads
local_backend:
  url: http://localhost:8080/api/v1
collections:
  - name: "updates" # Used in routes, e.g., /admin/collections/blog
    label: "Updates" # Used in the UI
    folder: "_posts/updates" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "update-{{year}}-{{month}}-{{day}}" # Filename template, e.g., YYYY-MM-DD-title.md
    editor:
      preview: false
    fields: # The fields for each document, usually in front matter
      - { label: "Layout", name: "layout", widget: "hidden", default: "blog" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Author(s)", name: "authors", widget: "string" }
      - { label: "Organisation", name: "organisation", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
